# ********************************************************************************
# Application Build Section :

# Provide the folder name to build the connectedhopeip
folder: v1.1 # NOTE : Make a directory named apps inside this folder

# Want to build connectedhomeip...?
Connectedhomeip: 'Y'

# Provide the branch name :
branch: master

# Need to switch commit provide the commit, if not N :
commit: 'N'

# Choose the sample apps to be build with Y, if not N :
all_clusters_app: 'Y'
all_clusters_minimal_app: 'Y'
bridge_app: 'N'
lock_app: 'N'
tv_app: 'N'
tv_casting_app: 'N'
lighting_app: 'N'
thermostat: 'N'
ota_provider_app: 'N'
ota_requestor_app: 'N'
chip_tool: 'Y'

# ********************************************************************************
# Execution Section :

# Path where chip-tool is located for execution 
chip_tool_directory: v1.1/apps

#Choose a cluster to execute with Y, If not N:
TVOCCONC: 'N'
NDOCONC: 'N'
CC: 'N'
LUNIT: 'N'
FLDCONC: 'N'
SWTCH: 'N'
BRBINFO: 'N'
BIND: 'N'
ULABEL: 'N'
PMICONC: 'N'
SMOKECO: 'N'
DISHM: 'N'
FLABEL: 'N'
DRLK: 'N'
ACFREMON: 'N'
TSTAT: 'N'
DESC: 'N'
MC: 'N'
CDOCONC: 'N'
PSCFG: 'N'
DGETH: 'N'
DGSW: 'N'
HEPAFREMON: 'N'
RVCCLEANM: 'N'
PRS: 'N'
I: 'N'
DGTHREAD: 'N'
BOOL: 'N'
TSUIC: 'N'
LCFG: 'N'
WNCV: 'N'
BINFO: 'N'
OCC: 'N'
DGWIFI: 'N'
GRPKEY: 'N'
RH: 'N'
PS: 'N'
LTIME: 'N'
G: 'N'
LWM: 'N'
PMHCONC: 'N'
PCC: 'N'
ACL: 'N'
RVCRUNM: 'N'
RNCONC: 'N'
FLW: 'N'
MOD: 'N'
LVL: 'N'
AIRQUAL: 'N'
PMKCONC: 'N'
TMP: 'N'
OZCONC: 'N'
FAN: 'N'
OO: 'N'
CMOCONC: 'N'
TCCM: 'N'
DGGEN: 'N'
ILL: 'N'
ACE: 'N'

# ********************************************************************************
# Cadmin Section :

Dut_data: {
  host: "192.168.8.101",
  username: "ubuntu",
  password: "raspberrypi",
  command: "./chip-all-clusters-app",
  path: "/home/ubuntu/oct16/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app"
  }

# ********************************************************************************
