- testcase: "[TC-LCFG-1.1]Global Attributes [DUT-Server]"
  commands:
    - command: "./chip-tool localizationconfiguration read cluster-revision 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read feature-map 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read  attribute-list 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read accepted-command-list 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read  generated-command-list 1 0"
      logs:
        - " "
- testcase: "[TC-LCFG-2.1] Localization Configuration Cluster Attributes"
  commands:
    - command: "./chip-tool localizationconfiguration read supported-locales 1 0"
      logs:
        - " "
    - command: "./chip-tool any write-by-id 0x002B 1 '\"xx-XX\"' 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read supported-locales 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read active-locale 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration write active-locale fw-GB 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration write active-locale fr-FR 1 0"
      logs:
        - " "
    - command: "./chip-tool localizationconfiguration read active-locale 1 0"
      logs:
        - " "
