- testcase: "[TC-PSCFG-1.1] Global attributes with server as DUT"
  commands:
    - command: "./chip-tool powersourceconfiguration read cluster-revision 1 0"
      logs:
        - " "
    - command: "./chip-tool powersourceconfiguration read feature-map 1 0"
      logs:
        - " "
    - command: "./chip-tool powersourceconfiguration read attribute-list 1 0"
      logs:
        - " "
    - command: "./chip-tool powersourceconfiguration read accepted-command-list 1 0"
      logs:
        - " "
    - command: "./chip-tool powersourceconfiguration read generated-command-list 1 0"
      logs:
        - " "
      logs:
        - " "
- testcase: "[TC-PSCFG-2.1] Global attributes with server as DUT"
  commands:
    - command: "./chip-tool powersourceconfiguration read sources 1 0"
      logs:
        - " "
      logs:
        - " "
- testcase: "[TC-PSCFG-2.2] Primary functionality with server as DUT"
  commands:
    - command: "./chip-tool powersourceconfiguration read sources 1 0"
      logs:
        - " "
    - command: "./chip-tool powersource read order 1 2"
      logs:
        - " "
    - command: "./chip-tool powersource read order 1 1"
      logs:
        - " "
    - command: "./chip-tool powersource read order 1 0"
      logs:
        - " "