name: Format YAML
on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  format-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install prettier
        run: npm install -g prettier @prettier/plugin-yaml

      - name: Auto-format YAML files
        run: prettier --write '**/*.yaml' '**/*.yml'

      - name: Check for changes
        run: |
          git diff --quiet || { git config --local user.email "suraj@graniteriverlabs.in" && git config --local user.name "Survensa" && git add . && git commit -m "Auto-format YAML files" && git push; }
