name: Validate YAML

on:
  push:
    branches:
      - main
    paths:
      - 'commands/**/*.yaml'
      - 'commands/**/*.yml'
  workflow_dispatch:

jobs:
  check_yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run YAML checker
      run: python src/validate_yaml.py
