name: Pull Test case summary from test plan html for Gsheet

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      TC_SUMMARY_SERVICE_ACCOUNT_JSON: ${{ secrets.TC_SUMMARY_SERVICE_ACCOUNT_JSON }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 gspread oauth2client PyGithub

    - name: Run Python script
      run: python -u src/tcd_g_py.py
