name: Pull TC_Summary

on:
  push:
    paths:
      - 'Docs/Test_Plan_HTML/*'  # Specify the path to your HTML files
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install openpyxl beautifulsoup4

      - name: Run Python Script
        run: |
          python src/tcd.py  # Replace with your script file name
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Excel File
        run: |
          git add Docs/TC_Summary.xlsx
          git commit -m "Update TC_Summary Excel file"
          git push
