name: Pull TC_Summary

on:
  push:
    branches:
      - main
    paths:
      - 'Docs/Test_Plan_HTML/*'  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  

      - name: Install dependencies
        run: pip install openpyxl beautifulsoup4

      - name: Run Python Script
        run: |
          python src/tcd.py  
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Excel File
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add Docs/TC_Summary.xlsx
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update TC_Summary Excel file - $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Convert Excel to HTML
        run: |
          python src/xlsxtohtml.py  
        working-directory: ${{ github.workspace }}

      - name: Commit and Push HTML File
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add Docs/TC_Summary.html
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update TC_Summary HTML file - $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Commit and Push JSON File
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add existing_data.json
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update existing_data JSON file - $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
