name: YAML Lint

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          find $GITHUB_WORKSPACE -name "*.yaml" -or -name "*.yml"
        shell: bash

      - name: Check YAML files for issues
        run: |
          for file in $(find $GITHUB_WORKSPACE -name "*.yaml" -or -name "*.yml"); do
            echo "Checking $file..."
            yamllint -c $GITHUB_WORKSPACE/.github/workflows/.yamllint "$file"
          done
        shell: bash
