name: Validate YAML

on:
  push:
    branches:
      - main
    paths:
      - '**.[yY][aA][mM][lL]'
  workflow_dispatch:

jobs:
  validate_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Validate YAML files
        run: |
          python src/validate_yaml.py ${{ github.workspace }}
