name: Python Lint 

on:
  workflow_run:
    workflows: ["Format Python"]
    types:
      - completed
  workflow_dispatch:

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install flake8
        run: |
          pip install flake8
        shell: bash

      - name: Lint Python code
        run: |
          flake8 .
        shell: bash
