name: YAML Lint

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          find $GITHUB_WORKSPACE -name "*.yaml" -or -name "*.yml"
        shell: bash

      - name: Check YAML files for issues
        run: |
          has_errors=false
          for file in $(find $GITHUB_WORKSPACE -name "*.yaml" -or -name "*.yml"); do
            echo "Checking $file..."
            if ! yamllint -c $GITHUB_WORKSPACE/.github/workflows/.yamllint "$file"; then
              has_errors=true
            fi
          done
          if [ "$has_errors" = true ]; then
            exit 1
          fi
        shell: bash
